// /blog/ index — generated from the live blog index HTML (34 posts). Posts themselves live on the live site.
export type Post = { slug: string; title: string; excerpt: string; tags: string; cats: ('ai' | 'mobile' | 'web' | 'strategy')[] }

export const BLOG_PAGE = {
  meta: {
    title: 'Blog — App Development Insights | Soni Consultancy Services',
    description: 'Practical guides on React Native, MERN and AI app development for founders and CTOs — costs, frameworks, architecture and AI strategy.',
  },
  hero: {
    crumb: 'Blog',
    eyebrow: 'Insights',
    title: 'From the studio.',
    lead: 'Practical, honest guides on React Native, MERN and AI app development — written for founders and product leaders who want to ship better software.',
  },
  featured: {
    kicker: '✦ Featured',
    title: "How to Build an AI-Powered React Native App in 2026",
    excerpt: "Where the model runs, how the pieces fit, what it costs and how long it takes — the complete founder's guide, with an interactive architecture explorer.",
    tags: 'Mobile · AI',
    read: '14 min read',
    slug: 'ai-react-native-app-development',
  },
  filters: [
    { key: 'all', label: 'All' },
    { key: 'ai', label: 'AI' },
    { key: 'mobile', label: 'Mobile' },
    { key: 'web', label: 'Web' },
    { key: 'strategy', label: 'Strategy' },
  ],
  readMore: 'Read more →',
  inline: {
    kicker: '✦ Work with us',
    title: 'Have a project in mind?',
    body: 'Book a free 30-minute call — we’ll map the fastest path from idea to a shipped product.',
    primary: 'Book a Free Call →',
    after: 'build-vs-buy-ai-cto-framework',
  },
  cta: {
    title: ['Got a product idea?', "Let's talk this week."],
    lead: '30 minutes. No pitch deck. An honest conversation about what you\'re building.',
    primary: 'Book a Free Call →',
    secondary: { label: 'See our work', href: '/work/' },
  },
}

export const POSTS: Post[] = [
  {"slug": "react-native-new-architecture-2026", "title": "React Native’s New Architecture in 2026: What Changed and How to Migrate", "excerpt": "0.82 disabled the old bridge, 0.85 removed it. Check how urgent migration is for you.", "tags": "Mobile · Engineering · Interactive", "cats": ["mobile", "strategy"]},
  {"slug": "rbi-fintech-app-compliance-india", "title": "RBI Compliance for Fintech Apps in India (2026)", "excerpt": "AFA and digital lending rules are live in 2026. Score your app against 10 requirements.", "tags": "Strategy · FinTech · Interactive", "cats": ["strategy", "mobile"]},
  {"slug": "react-native-push-notifications", "title": "React Native Push Notifications: Firebase, OneSignal or Notifee in 2026", "excerpt": "OneSignal’s free tier just shrank. See the real cost at your user count.", "tags": "Mobile · Engineering · Interactive", "cats": ["mobile"]},
  {"slug": "kotlin-multiplatform-vs-react-native", "title": "Kotlin Multiplatform vs React Native (2026): Which Should You Pick?", "excerpt": "KMP adoption is climbing fast. Answer 5 questions for a recommendation on your project.", "tags": "Mobile · Interactive", "cats": ["mobile", "strategy"]},
  {"slug": "dpdp-act-app-compliance-india", "title": "India’s DPDP Act for Apps (2026): Deadlines and a Readiness Check", "excerpt": "Full enforcement lands May 2027. Score your app against 10 controls and see what to fix first.", "tags": "Strategy · Compliance · Interactive", "cats": ["strategy", "mobile"]},
  {"slug": "can-ai-build-my-app", "title": "Can AI Build My App? An Honest 2026 Answer for Founders", "excerpt": "What AI genuinely accelerates, what it still cannot own — and which side your project falls on.", "tags": "AI · Strategy · Interactive", "cats": ["ai", "strategy"]},
  {"slug": "super-app-development", "title": "Super Apps and Mini Apps in 2026: Should Your Product Become a Platform?", "excerpt": "The model works only under specific conditions. Answer 5 questions to see if yours qualify.", "tags": "Mobile · Strategy · Interactive", "cats": ["mobile", "strategy"]},
  {"slug": "wordpress-website-cost-india", "title": "WordPress Website Cost in India (2026): Real Numbers + Calculator", "excerpt": "Real market pricing by project type — and a calculator to estimate your own build.", "tags": "Web · Interactive · Cost", "cats": ["web", "strategy"]},
  {"slug": "wordpress-vs-custom-website", "title": "WordPress vs Custom Website in 2026: Which Should You Build?", "excerpt": "Answer 5 questions, get an honest recommendation — from a team that builds both.", "tags": "Web · Interactive", "cats": ["web", "strategy"]},
  {"slug": "woocommerce-payment-gateway-india", "title": "Razorpay vs PayU vs Cashfree: Best Gateway for WooCommerce India", "excerpt": "2026 fees, plugin status and settlements compared — with live fee math for your volume.", "tags": "Web · E-commerce", "cats": ["web", "strategy"]},
  {"slug": "wordpress-seo-speed-checklist", "title": "WordPress Speed & SEO Checklist 2026: Score Your Site in 2 Minutes", "excerpt": "10 controls, a live score, and what to fix first — run the free self-audit.", "tags": "Web · SEO · Interactive", "cats": ["web"]},
  {"slug": "native-vs-cross-platform-2026", "title": "Native vs Cross-Platform in 2026: An Interactive Decision Tool", "excerpt": "Answer 5 questions, get a recommendation — native, React Native or Flutter — for your app.", "tags": "Mobile · Interactive", "cats": ["mobile", "strategy"]},
  {"slug": "mvp-tech-stack-2026", "title": "How to Choose Your MVP Tech Stack in 2026", "excerpt": "Answer 5 questions — get frontend, backend, database and hosting for your product.", "tags": "Strategy · Interactive", "cats": ["strategy", "mobile", "web"]},
  {"slug": "mobile-app-security-checklist", "title": "Mobile App Security Checklist 2026: Score Your App in 2 Minutes", "excerpt": "10 controls, a live score, and the fixes that matter first — run the free self-audit.", "tags": "Mobile · Security", "cats": ["mobile"]},
  {"slug": "app-monetization-models", "title": "App Monetization Models 2026: Interactive Revenue Explorer", "excerpt": "Subscription, IAP, ads or commission — drag the sliders and see the math for your app.", "tags": "Strategy · Revenue", "cats": ["strategy"]},
  {"slug": "how-long-to-build-an-app", "title": "How Long Does It Take to Build a Mobile App in 2026?", "excerpt": "A realistic timeline by phase — MVP vs full build, what drives the schedule, and why estimates slip.", "tags": "Mobile · Timeline", "cats": ["mobile", "strategy"]},
  {"slug": "ci-cd-react-native", "title": "CI/CD for React Native Apps: A 2026 Setup Guide", "excerpt": "Automated build, test, signing and store releases — plus OTA updates for the fast lane.", "tags": "DevOps · Mobile", "cats": ["mobile"]},
  {"slug": "validate-app-idea-before-building", "title": "How to Validate Your App Idea Before You Build It", "excerpt": "The cheap way to find out people want your app — before you spend a development budget.", "tags": "Strategy · Product", "cats": ["strategy"]},
  {"slug": "app-store-launch-checklist", "title": "App Store & Google Play Launch: A 2026 Submission Checklist", "excerpt": "Everything between a finished build and a live app — accounts, listings, privacy labels and review.", "tags": "Mobile · Launch", "cats": ["mobile", "strategy"]},
  {"slug": "app-maintenance-cost", "title": "What App Maintenance Really Costs After Launch", "excerpt": "Apps aren't \"done\" at launch — the real ongoing cost of keeping one alive, and how to keep it down.", "tags": "Strategy · Cost", "cats": ["strategy", "mobile"]},
  {"slug": "aws-cloud-migration-guide", "title": "AWS Cloud Migration: A Practical Guide for 2026", "excerpt": "The 6 R's, lift-and-shift vs re-architecture, a roadmap and how to control cloud cost.", "tags": "Cloud · Migration", "cats": ["web", "strategy"]},
  {"slug": "bsa-aml-software-build-vs-buy", "title": "BSA/AML Software: Build vs Buy in 2026", "excerpt": "When to buy, when to build, and the architecture and compliance that decide it.", "tags": "FinTech · Compliance", "cats": ["strategy"]},
  {"slug": "react-native-app-development-cost", "title": "React Native App Development Cost in 2026", "excerpt": "A transparent breakdown by complexity, the hidden costs, and how to budget from MVP to scale.", "tags": "Mobile · Cost", "cats": ["mobile", "strategy"]},
  {"slug": "hire-react-native-developers", "title": "How to Hire React Native Developers in 2026", "excerpt": "In-house vs freelance vs agency, the skills to screen for, and what it really costs.", "tags": "Mobile · Hiring", "cats": ["mobile", "strategy"]},
  {"slug": "ai-agent-development-services", "title": "AI Agent Development Services in 2026", "excerpt": "What agents are, what they cost, and how to build one that delivers outcomes — not demos.", "tags": "AI · Agents", "cats": ["ai"]},
  {"slug": "ai-app-development-cost-2026", "title": "How Much Does It Cost to Build an AI App in 2026?", "excerpt": "A real pricing breakdown for founders and CTOs — no vague \"it depends.\"", "tags": "AI · Cost", "cats": ["ai", "strategy"]},
  {"slug": "build-vs-buy-ai-cto-framework", "title": "Build vs Buy AI: A CTO's Decision Framework", "excerpt": "The most expensive AI mistake is building what you should have bought.", "tags": "AI · CTO Strategy", "cats": ["ai", "strategy"]},
  {"slug": "react-native-vs-flutter-2026", "title": "React Native vs Flutter in 2026: Which Should You Choose?", "excerpt": "An honest comparison from a studio that ships both.", "tags": "Mobile · Framework", "cats": ["mobile"]},
  {"slug": "nextjs-saas-architecture", "title": "Next.js SaaS Architecture: The Patterns We Use", "excerpt": "Multi-tenancy, RBAC, API layers, Stripe — the patterns behind every SaaS we ship.", "tags": "Web · Architecture", "cats": ["web"]},
  {"slug": "mvp-to-product-market-fit", "title": "From MVP to Product-Market Fit: What Changes After Launch", "excerpt": "The mistakes founders make in the first 90 days — and how to find traction faster.", "tags": "Strategy · Product", "cats": ["strategy"]},
  {"slug": "ai-react-native-app-development", "title": "How to Build an AI-Powered React Native App in 2026", "excerpt": "Where the model runs, how it's wired, what it costs — the complete guide.", "tags": "Mobile · AI", "cats": ["mobile", "ai"]},
  {"slug": "react-native-chatgpt-integration", "title": "Integrating ChatGPT & LLMs into a React Native App", "excerpt": "The right way: secure proxy, streaming responses and cost control.", "tags": "Mobile · AI", "cats": ["mobile", "ai"]},
  {"slug": "on-device-ai-react-native", "title": "On-Device AI in React Native: Private, Offline, $0 per Call", "excerpt": "Run models on the phone — privacy, offline and no per-call cost.", "tags": "Mobile · AI", "cats": ["mobile", "ai"]},
  {"slug": "ai-chatbot-app-react-native", "title": "Building an AI Chatbot App with React Native", "excerpt": "The four complexity tiers, realistic timelines and what drives cost.", "tags": "Mobile · AI", "cats": ["mobile", "ai"]},
]
