#!/usr/bin/env python3
"""
Static generator for outreach.soniconsultancyservices.com.

    python3 build.py                 regenerate every page into public/
    python3 build.py --check         exit 1 if public/ is stale against content/ + data/
    python3 build.py --assets        also render the PDFs and share images (needs Chrome)
    python3 build.py --preview DIR   self-contained copy with relative links, forms in dry run

Standard library only (Python 3.9+). Content lives in content/*.md, every
number lives in data/stats.json, and public/ is the deploy artifact.
Generated files carry a "generated by build.py" comment. Edit the source,
never the output.
"""

import argparse
import base64
import datetime as dt
import hashlib
import html
import json
import math
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CONTENT = ROOT / "content"
DATA = ROOT / "data"
PUBLIC = ROOT / "public"
TEMPLATES = ROOT / "templates"

GENERATED_NOTE = "<!-- generated by build.py from {src}. Edit the source, not this file. -->"
TITLE_MAX, DESC_MAX = 60, 160
WPM = 230

# Brief targets, checked on every build (a miss is printed as a warning).
WORD_TARGETS = {
    "the-audit": (2000, None),
    "signal-based-targeting": (600, 800),
    "audit-first-method": (600, 800),
    "what-failed": (600, 800),
    "the-quest-email": (500, 700),
}


class BuildError(Exception):
    pass


def esc(s):
    return html.escape(str(s), quote=False)


def attr(s):
    return html.escape(str(s), quote=True)


def strip_tags(s):
    return html.unescape(re.sub(r"<[^>]+>", "", s))


def slugify(s):
    s = s.lower().replace("&", " and ")
    s = re.sub(r"[‘’“”'\"]", "", s)
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-") or "section"


def fmt_date(iso):
    d = dt.date.fromisoformat(iso)
    return f"{d.day} {d.strftime('%b')} {d.year}"


# --------------------------------------------------------------------- icons
# Inline SVG, stroke = currentColor, always decorative (text carries meaning).
def _icon(body, cls="i"):
    return (f'<svg class="{cls}" viewBox="0 0 24 24" width="16" height="16" aria-hidden="true" '
            f'focusable="false" fill="none" stroke="currentColor" stroke-width="2" '
            f'stroke-linecap="round" stroke-linejoin="round">{body}</svg>')


ICON = {
    "check": _icon('<path d="M5 12.5l4.5 4.5L19 7.5"/>'),
    "x": _icon('<path d="M6.5 6.5l11 11M17.5 6.5l-11 11"/>'),
    "arrow": _icon('<path d="M5 12h14M13 6l6 6-6 6"/>'),
    "download": _icon('<path d="M12 4v11M7 10.5l5 5 5-5M5 20h14"/>'),
    "sun": _icon('<circle cx="12" cy="12" r="4"/><path d="M12 2.5v2M12 19.5v2M4.6 4.6l1.4 1.4M18 18l1.4 1.4M2.5 12h2M19.5 12h2M4.6 19.4L6 18M18 6l1.4-1.4"/>', "i i-sun"),
    "moon": _icon('<path d="M20 14.5A8 8 0 0 1 9.5 4a8 8 0 1 0 10.5 10.5z"/>', "i i-moon"),
    "link": _icon('<path d="M10 14a4.5 4.5 0 0 0 6.4 0l3-3a4.5 4.5 0 0 0-6.4-6.4l-1 1"/><path d="M14 10a4.5 4.5 0 0 0-6.4 0l-3 3a4.5 4.5 0 0 0 6.4 6.4l1-1"/>'),
    "share": _icon('<circle cx="18" cy="5" r="2.5"/><circle cx="6" cy="12" r="2.5"/><circle cx="18" cy="19" r="2.5"/><path d="M8.2 10.8l7.6-4.4M8.2 13.2l7.6 4.4"/>'),
}


# ---------------------------------------------------------------------- data
TOKEN_RE = re.compile(r"\{\{\s*([a-z_]+)(?:\.([a-z]+))?\s*\}\}")


def load_data():
    stats = json.loads((DATA / "stats.json").read_text("utf-8"))
    site = json.loads((DATA / "site.json").read_text("utf-8"))
    tokens = {}
    for section in ("audit", "method"):
        for key, entry in stats[section].items():
            if key.startswith("_"):
                continue
            if key in tokens:
                raise BuildError(f"stats.json: duplicate key '{key}'")
            tokens[key] = entry
    window = stats["method"]["window_days"]["value"]
    if not any(b.get("max_days") == window for b in stats["scorer"]["timing"]):
        raise BuildError(
            f"stats.json: scorer.timing has no band ending at window_days ({window}). "
            "Update the timing bands so one of them ends where the window ends.")
    return stats, site, tokens


def resolve_tokens(text, tokens, where):
    def sub(m):
        key, field = m.group(1), m.group(2) or "display"
        if key not in tokens:
            raise BuildError(f"{where}: unknown stat token {{{{{key}}}}}")
        if field not in tokens[key]:
            raise BuildError(f"{where}: stat '{key}' has no '{field}' field")
        return str(tokens[key][field])
    return TOKEN_RE.sub(sub, text)


def lint_hardcoded(text, tokens, where):
    """Numbers from stats.json must be referenced, never typed into content."""
    problems = []
    bare = TOKEN_RE.sub(" ", text)
    for key, entry in tokens.items():
        shown = str(entry.get("display", ""))
        if not re.search(r"\d", shown) or shown in ("0", "1"):
            continue
        tail = r"(?![\w])" if shown[-1].isalnum() else ""
        for m in re.finditer(r"(?<![\w.])" + re.escape(shown) + tail, bare):
            line = bare.count("\n", 0, m.start()) + 1
            problems.append(f'{where}:{line}: "{shown}" is hardcoded. Use {{{{{key}}}}} from data/stats.json.')
    return problems


def parse_front_matter(text, where):
    if not text.startswith("---\n"):
        raise BuildError(f"{where}: missing front matter")
    end = text.find("\n---\n", 4)
    if end == -1:
        raise BuildError(f"{where}: unterminated front matter")
    meta = {}
    for line in text[4:end].split("\n"):
        if not line.strip():
            continue
        key, sep, value = line.partition(":")
        if not sep:
            raise BuildError(f"{where}: bad front matter line: {line!r}")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        meta[key.strip()] = value
    return meta, text[end + 5:]


def word_count(md):
    text = "\n".join(l for l in md.split("\n") if not re.match(r"^\s*:{3,}", l))
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"[#>*`_]", " ", text)
    return sum(1 for w in text.split() if re.search(r"\w", w))


# ------------------------------------------------------------------ typography
def _opening_context(s, i):
    if i == 0:
        return True
    p = s[i - 1]
    if p == ">":
        k = s.rfind("<", 0, i)
        return not (k != -1 and s[k + 1:k + 2] == "/")
    if p == "\x00":
        return False
    return p.isspace() or p in "([{—–-/“‘"


def smarten(s):
    """Curly quotes and apostrophes, skipping anything inside tags."""
    out, in_tag = [], False
    for i, ch in enumerate(s):
        if ch == "<":
            in_tag = True
        elif ch == ">" and in_tag:
            in_tag = False
            out.append(ch)
            continue
        if in_tag or ch not in "\"'":
            out.append(ch)
            continue
        opening = _opening_context(s, i)
        if ch == '"':
            out.append("“" if opening else "”")
        else:
            nxt = s[i + 1] if i + 1 < len(s) else " "
            out.append("‘" if opening and not nxt.isspace() else "’")
    return "".join(out)


# -------------------------------------------------------------------- context
class Ctx:
    """Knows where a page lives, so links can be absolute (production) or
    relative (file/preview builds, which have no server to resolve /dir/)."""

    def __init__(self, page_path, preview, site, versions):
        self.page_path = page_path            # e.g. "articles/the-audit/index.html"
        self.preview = preview
        self.site = site
        self.versions = versions

    def url(self, href):
        if not href.startswith("/") or href.startswith("//"):
            return href
        if not self.preview:
            return href
        path, _, frag = href.partition("#")
        path, _, query = path.partition("?")
        target = path.lstrip("/")
        if target == "" or target.endswith("/"):
            target += "index.html"
        base = os.path.dirname(self.page_path) or "."
        rel = os.path.relpath(target, base)
        return rel + ("?" + query if query else "") + ("#" + frag if frag else "")

    def asset(self, path):
        v = self.versions.get(path)
        return self.url(path) + (f"?v={v}" if v and not self.preview else "")

    def canonical(self, path):
        return self.site["base_url"] + path


# ------------------------------------------------------------------- markdown
FENCE_RE = re.compile(r"^(:{3,})\s*([A-Za-z][\w-]*)?\s*(.*)$")
ATTR_RE = re.compile(r'([\w-]+)="([^"]*)"')


class Markdown:
    """A deliberately small Markdown subset plus :::directives.
    Supported: ## / ### / #### headings, paragraphs, - and 1. lists,
    > blockquotes, ``` code, **bold**, *italic*, `code`, [links](url),
    {{stat}} tokens, and fenced directives (:::name attr="v" ... :::)."""

    def __init__(self, page, build):
        self.page = page
        self.build = build
        self.ctx = page.ctx
        self.tokens = build.tokens
        self.headings = []
        self.ids = set()
        self.counter = 0

    # blocks -----------------------------------------------------------------
    def render(self, text):
        return "\n".join(self.blocks(text.split("\n")))

    @staticmethod
    def starts_block(s):
        return bool(re.match(r"^(#{2,4}\s|>|[-*]\s|\d+\.\s|```|:{3,}|---$)", s))

    def blocks(self, lines):
        out, i, n = [], 0, len(lines)
        while i < n:
            s = lines[i].strip()
            if not s:
                i += 1
                continue
            m = FENCE_RE.match(s)
            if m and m.group(2):
                fence, name = m.group(1), m.group(2)
                attrs = dict(ATTR_RE.findall(m.group(3) or ""))
                j = i + 1
                while j < n and lines[j].strip() != fence:
                    j += 1
                if j >= n:
                    raise BuildError(f"{self.page.src}: unclosed :::{name}")
                out.append(self.directive(name, attrs, lines[i + 1:j]))
                i = j + 1
                continue
            if s.startswith("```"):
                j = i + 1
                while j < n and not lines[j].strip().startswith("```"):
                    j += 1
                out.append(f"<pre><code>{esc(chr(10).join(lines[i + 1:j]))}</code></pre>")
                i = j + 1
                continue
            hm = re.match(r"^(#{2,4})\s+(.*)$", s)
            if hm:
                out.append(self.heading(len(hm.group(1)), hm.group(2)))
                i += 1
                continue
            if s.startswith(">"):
                buf, j = [], i
                while j < n and lines[j].strip().startswith(">"):
                    buf.append(re.sub(r"^\s*>\s?", "", lines[j]))
                    j += 1
                out.append("<blockquote>" + "\n".join(self.blocks(buf)) + "</blockquote>")
                i = j
                continue
            if re.match(r"^[-*]\s+", s):
                items, i = self.collect_list(lines, i, r"^[-*]\s+")
                out.append("<ul>" + "".join(f"<li>{self.inline(t)}</li>" for t in items) + "</ul>")
                continue
            om = re.match(r"^(\d+)\.\s+", s)
            if om:
                start = int(om.group(1))
                items, i = self.collect_list(lines, i, r"^\d+\.\s+")
                st = "" if start == 1 else f' start="{start}"'
                out.append(f"<ol{st}>" + "".join(f"<li>{self.inline(t)}</li>" for t in items) + "</ol>")
                continue
            if s == "---":
                out.append("<hr>")
                i += 1
                continue
            buf, j = [s], i + 1
            while j < n and lines[j].strip() and not self.starts_block(lines[j].strip()):
                buf.append(lines[j].strip())
                j += 1
            out.append(f"<p>{self.inline(' '.join(buf))}</p>")
            i = j
        return out

    @staticmethod
    def collect_list(lines, i, marker):
        items, n = [], len(lines)
        while i < n:
            s = lines[i].strip()
            if not s:
                k = i + 1
                while k < n and not lines[k].strip():
                    k += 1
                if k < n and re.match(marker, lines[k].strip()):
                    i = k
                    continue
                break
            if re.match(marker, s):
                items.append(re.sub(marker, "", s, count=1))
            elif lines[i][:1] in (" ", "\t") and items:
                items[-1] += " " + s
            else:
                break
            i += 1
        return items, i

    def unique_id(self, base):
        hid, k = base, 2
        while hid in self.ids:
            hid, k = f"{base}-{k}", k + 1
        self.ids.add(hid)
        return hid

    def heading(self, level, raw):
        inner = self.inline(raw)
        hid = self.unique_id(slugify(strip_tags(inner)))
        self.headings.append((level, strip_tags(inner), hid))
        return f'<h{level} id="{hid}">{inner}</h{level}>'

    # inline -----------------------------------------------------------------
    def inline(self, text):
        text = resolve_tokens(text, self.tokens, self.page.src)
        stash = []

        def keep(fragment):
            stash.append(fragment)
            return f"\x00{len(stash) - 1}\x00"

        text = re.sub(r"`([^`]+)`", lambda m: keep(f"<code>{esc(m.group(1))}</code>"), text)
        text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", lambda m: keep(self.link(m.group(1), m.group(2))), text)
        text = smarten(self.emph(esc(text)))
        return re.sub(r"\x00(\d+)\x00", lambda m: stash[int(m.group(1))], text)

    @staticmethod
    def emph(s):
        s = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", s)
        return re.sub(r"(?<![*\w])\*(?!\s)(.+?)(?<!\s)\*(?![*\w])", r"<em>\1</em>", s)

    def link(self, label, href):
        inner = smarten(self.emph(esc(label)))
        external = href.startswith("http")
        rel = ' rel="noopener"' if external else ""
        return f'<a href="{attr(self.ctx.url(href))}"{rel}>{inner}</a>'

    # directives ---------------------------------------------------------------
    def directive(self, name, attrs, inner):
        fn = getattr(self, "d_" + name.replace("-", "_"), None)
        if fn is None:
            raise BuildError(f"{self.page.src}: unknown directive :::{name}")
        self.build.directive_use.setdefault(name, []).append(self.page.path)
        return fn(attrs, inner)

    def d_steps(self, attrs, inner):
        return '<div class="steps">' + "".join(self.blocks(inner)) + "</div>"

    def d_more(self, attrs, inner):
        label = attrs.get("label", "Deep dive")
        return (f'<aside class="more"><p class="more-label">{esc(label)}</p>'
                + "".join(self.blocks(inner)) + "</aside>")

    def d_check(self, attrs, inner):
        self.counter += 1
        cid = f"check-{self.counter}"
        text = " ".join(l.strip() for l in inner if l.strip())
        return (f'<div class="check"><input type="checkbox" id="{cid}">'
                f'<label for="{cid}"><span class="check-kicker">Check yourself</span> '
                f"{self.inline(text)}</label></div>")

    def d_stats(self, attrs, inner):
        return self.build.render_count(self.ctx)

    def d_timeline(self, attrs, inner):
        return self.build.render_timeline()

    def d_compare(self, attrs, inner):
        return '<div class="compare">' + "".join(self.blocks(inner)) + "</div>"

    def d_annotated(self, attrs, inner):
        tone = attrs.get("tone", "bad")
        pairs = []
        for raw in inner:
            s = raw.strip()
            if not s:
                continue
            if s.startswith(">"):
                pairs.append([s[1:].strip(), ""])
            elif not pairs:
                raise BuildError(f"{self.page.src}: annotation before the first > email line")
            else:
                pairs[-1][1] = (pairs[-1][1] + " " + s).strip()
        rows = "".join(
            f'<li class="ann-row"><span class="ann-n" aria-hidden="true">{n}</span>'
            f'<p class="ann-line">{self.inline(line)}</p>'
            f'<p class="ann-note">{self.inline(note)}</p></li>'
            for n, (line, note) in enumerate(pairs, 1))
        icon = ICON["x"] if tone == "bad" else ICON["check"]
        return (f'<section class="ann ann--{attr(tone)}" aria-label="{attr(attrs.get("title", ""))}">'
                f'<header class="ann-head"><p class="ann-title">{esc(attrs.get("title", ""))}</p>'
                f'<p class="ann-source">{esc(attrs.get("source", ""))}</p>'
                f'<p class="ann-verdict">{icon}<span>{esc(attrs.get("verdict", ""))}</span></p></header>'
                f'<ol class="ann-rows">{rows}</ol></section>')

    def d_tool_cards(self, attrs, inner):
        return self.build.render_tool_cards(self.ctx)

    def d_scorer_app(self, attrs, inner):
        return self.build.render_scorer_app(self.ctx)

    def d_scorer_weights(self, attrs, inner):
        return self.build.render_scorer_weights()

    def d_crm_app(self, attrs, inner):
        return self.build.render_crm_app(self.ctx)

    def d_template_download(self, attrs, inner):
        return self.build.render_template_download(self.ctx)

    def d_studio_cta(self, attrs, inner):
        return self.build.render_studio_cta(self.ctx)


# ---------------------------------------------------------------------- pages
class Page:
    def __init__(self, path, src, kind, meta, body_md, ctx):
        self.path = path          # output path relative to the site root
        self.src = src            # source file, for messages
        self.kind = kind
        self.meta = meta
        self.body_md = body_md
        self.ctx = ctx
        self.url = "/" + path[: -len("index.html")] if path.endswith("index.html") else "/" + path


class Build:
    def __init__(self, out_dir, preview=False, inline_fonts=False):
        self.out = Path(out_dir)
        self.preview = preview
        self.inline_fonts = inline_fonts
        self.stats, self.site, self.tokens = load_data()
        self.directive_use = {}
        self.written = []
        self.warnings = []
        self.versions = {}
        for rel in ("/assets/css/site.css", "/assets/js/site.js", "/assets/js/score.js",
                    "/assets/js/scorer.js", "/assets/js/crm.js"):
            f = PUBLIC / rel.lstrip("/")
            if f.exists():
                self.versions[rel] = hashlib.md5(f.read_bytes()).hexdigest()[:8]

    # helpers --------------------------------------------------------------
    def t(self, text, where="template"):
        return resolve_tokens(text, self.tokens, where)

    def ctx(self, path):
        return Ctx(path, self.preview, self.site, self.versions)

    def write(self, rel, content):
        dest = self.out / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, "utf-8")
        self.written.append(rel)

    # content ---------------------------------------------------------------
    def load_articles(self):
        problems, articles = [], []
        for f in sorted((CONTENT / "articles").glob("*.md")):
            raw = f.read_text("utf-8")
            problems += lint_hardcoded(raw, self.tokens, f"content/articles/{f.name}")
            meta, body = parse_front_matter(raw, f.name)
            meta = {k: smarten(self.t(v, f.name)) for k, v in meta.items()}
            meta["slug"] = f.stem
            meta["order"] = int(meta.get("order", 99))
            meta["words"] = word_count(self.t(body, f.name))
            meta["minutes"] = max(1, math.ceil(meta["words"] / WPM))
            path = f"articles/{f.stem}/index.html"
            articles.append(Page(path, f"content/articles/{f.name}", "article", meta, body, self.ctx(path)))
        for f in sorted(CONTENT.glob("*.md")) + sorted((CONTENT / "tools").glob("*.md")):
            problems += lint_hardcoded(f.read_text("utf-8"), self.tokens, str(f.relative_to(ROOT)))
        if problems:
            raise BuildError("hardcoded statistics found:\n  " + "\n  ".join(problems))
        articles.sort(key=lambda p: p.meta["order"])
        return articles

    def load_page(self, rel_src, out_path, kind):
        f = CONTENT / rel_src
        meta, body = parse_front_matter(f.read_text("utf-8"), rel_src)
        meta = {k: smarten(self.t(v, rel_src)) for k, v in meta.items()}
        return Page(out_path, f"content/{rel_src}", kind, meta, body, self.ctx(out_path))

    # shared chrome ----------------------------------------------------------
    def head(self, page, title, desc, og_type, og_image, jsonld, scripts=()):
        c = page.ctx
        canonical = c.canonical(page.url)
        full_title = title
        suffix = " · " + self.site["name"]
        if page.kind != "home" and len(title + suffix) <= TITLE_MAX:
            full_title = title + suffix
        if len(full_title) > TITLE_MAX:
            self.warnings.append(f"{page.path}: title is {len(full_title)} chars (> {TITLE_MAX})")
        if len(desc) > DESC_MAX:
            self.warnings.append(f"{page.path}: description is {len(desc)} chars (> {DESC_MAX})")
        og_img = self.site["base_url"] + og_image
        og_title = page.meta.get("og_title") or page.meta.get("title", title)
        robots = "noindex,follow" if page.kind == "404" else "index,follow"
        a = self.site["author"]
        lines = [
            "<!doctype html>",
            f'<html lang="{self.site["lang"]}" data-page="{page.kind}">',
            "<head>",
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">',
            f"<title>{esc(full_title)}</title>",
            f'<meta name="description" content="{attr(desc)}">',
            f'<meta name="robots" content="{robots}">',
            f'<meta name="author" content="{attr(a["name"])}">',
            f'<link rel="canonical" href="{attr(canonical)}">',
            f'<meta property="og:site_name" content="{attr(self.site["name"])}">',
            f'<meta property="og:type" content="{og_type}">',
            f'<meta property="og:title" content="{attr(og_title)}">',
            f'<meta property="og:description" content="{attr(desc)}">',
            f'<meta property="og:url" content="{attr(canonical)}">',
            f'<meta property="og:image" content="{attr(og_img)}">',
            '<meta property="og:image:width" content="1200">',
            '<meta property="og:image:height" content="630">',
            f'<meta property="og:image:alt" content="{attr(og_title)}">',
            '<meta property="og:locale" content="en_US">',
        ]
        if og_type == "article":
            lines += [
                f'<meta property="article:published_time" content="{page.meta.get("date", self.site["published"])}">',
                f'<meta property="article:author" content="{attr(a["linkedin"])}">',
            ]
        lines += [
            '<meta name="twitter:card" content="summary_large_image">',
            f'<meta name="twitter:title" content="{attr(og_title)}">',
            f'<meta name="twitter:description" content="{attr(desc)}">',
            f'<meta name="twitter:image" content="{attr(og_img)}">',
            '<meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">',
            '<meta name="theme-color" content="#101319" media="(prefers-color-scheme: dark)">',
            f'<link rel="icon" href="{c.url("/favicon.svg")}" type="image/svg+xml">',
        ]
        if not (self.preview and self.inline_fonts):
            for font in ("newsreader-latin-var", "schibsted-grotesk-latin-var"):
                lines.append(f'<link rel="preload" href="{c.url("/assets/fonts/" + font + ".woff2")}" '
                             'as="font" type="font/woff2" crossorigin>')
        lines.append(f'<link rel="stylesheet" href="{c.asset("/assets/css/site.css")}">')
        lines.append("<script>" + THEME_BOOT + "</script>")
        lines.append('<script type="application/ld+json">'
                     + json.dumps(jsonld, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
                     + "</script>")
        for s in ("/assets/js/site.js",) + tuple(scripts):
            lines.append(f'<script src="{c.asset(s)}" defer></script>')
        lines.append("</head>")
        return "\n".join(lines)

    def masthead(self, page):
        c = page.ctx
        def nav(href, label):
            cur = page.url == href or (href != "/" and page.url.startswith(href))
            aria = ' aria-current="page"' if cur else ""
            return f'<a href="{c.url(href)}"{aria}>{label}</a>'
        return (
            '<a class="skip" href="#main">Skip to content</a>\n'
            '<header class="masthead"><div class="masthead-in">'
            f'<a class="wordmark" href="{c.url("/")}"><span class="wordmark-name">{esc(self.site["name"])}</span>'
            f'<span class="wordmark-by">by {esc(self.site["author"]["name"])}</span></a>'
            f'<nav class="nav" aria-label="Site">{nav("/articles/", "Articles")}{nav("/tools/", "Tools")}'
            '<button class="theme-toggle" type="button" data-theme-toggle aria-label="Use dark theme">'
            f'{ICON["moon"]}{ICON["sun"]}</button></nav>'
            "</div></header>")

    def newsletter_form(self, fid, variant):
        """Layer 1: newsletter. Rendered in the footer of every page and at the end of every article."""
        big = variant == "article"
        heading = ('<h2 class="capture-title" id="nl-{0}-h">Get the next teardown</h2>'
                   '<p class="capture-text">New teardowns when they’re written. One email each, nothing else.</p>'
                   if big else
                   '<p class="capture-title" id="nl-{0}-h">Future teardowns, by email</p>').format(fid)
        return (
            f'<form class="capture-form subscribe subscribe--{variant}" data-capture="newsletter" '
            f'aria-labelledby="nl-{fid}-h" novalidate>'
            f"{heading}"
            f'<div class="field-row"><label class="sr-only" for="nl-{fid}-email">Email address</label>'
            f'<input id="nl-{fid}-email" name="email" type="email" autocomplete="email" inputmode="email" '
            'placeholder="you@company.com" required>'
            '<button class="btn" type="submit">Subscribe</button></div>'
            '<p class="fine">Only when there’s a new one. Unsubscribe anytime. '
            f'<a href="{attr(self.site["studio"]["privacy_url"])}" rel="noopener">Privacy</a></p>'
            f'<div class="hp" aria-hidden="true"><label for="nl-{fid}-web">Leave this empty</label>'
            f'<input id="nl-{fid}-web" name="website" type="text" tabindex="-1" autocomplete="off"></div>'
            '<p class="form-msg" role="status" aria-live="polite"></p>'
            '<p class="form-done" hidden>You’re subscribed. The next teardown will land in your inbox.</p>'
            "</form>")

    def footer(self, page):
        c = page.ctx
        s = self.site
        return (
            '<footer class="site-foot"><div class="foot-in">'
            f'<div class="foot-capture">{self.newsletter_form("foot", "foot")}</div>'
            '<nav class="foot-nav" aria-label="Footer">'
            f'<a href="{c.url("/articles/")}">Articles</a>'
            f'<a href="{c.url("/tools/")}">Tools</a>'
            '<button class="linkish" type="button" data-gate="playbook">The playbook (PDF)</button>'
            f'<a href="{attr(s["author"]["linkedin"])}" rel="noopener">LinkedIn</a>'
            "</nav>"
            f'<p class="byline"><a href="{attr(s["studio"]["url"])}" rel="noopener">'
            f'Built by {esc(s["author"]["name"])}, founder of {esc(s["studio"]["name"])}</a></p>'
            "</div></footer>")

    def gates(self, page):
        """Layers 2 and 3: gated downloads, one <dialog> each, opened by [data-gate]."""
        c = page.ctx
        d = self.site["downloads"]
        def gate(gid, kicker, title, text, want, links):
            dl = "".join(
                f'<a class="btn btn--dl" href="{attr(c.url(href))}" download data-file="{attr(name)}">'
                f'{ICON["download"]}<span>{esc(label)}</span></a>' for label, href, name in links)
            return (
                f'<dialog class="gate" id="gate-{gid}" aria-labelledby="gate-{gid}-h">'
                '<form method="dialog" class="gate-close-form"><button class="gate-close" aria-label="Close">'
                f'{ICON["x"]}</button></form>'
                f'<p class="gate-kicker">{esc(kicker)}</p>'
                f'<h2 class="gate-title" id="gate-{gid}-h">{esc(title)}</h2>'
                f'<p class="gate-text">{esc(text)}</p>'
                f'<form class="capture-form gate-form" data-capture="{gid}" data-want="{attr(want)}" novalidate>'
                f'<label class="field-label" for="gate-{gid}-email">Your email</label>'
                f'<div class="field-row"><input id="gate-{gid}-email" name="email" type="email" '
                'autocomplete="email" inputmode="email" placeholder="you@company.com" required>'
                '<button class="btn" type="submit">Get it</button></div>'
                f'<label class="optin" for="gate-{gid}-optin"><input id="gate-{gid}-optin" name="optin" '
                'type="checkbox"> Also email me new teardowns (unsubscribe anytime)</label>'
                f'<div class="hp" aria-hidden="true"><label for="gate-{gid}-web">Leave this empty</label>'
                f'<input id="gate-{gid}-web" name="website" type="text" tabindex="-1" autocomplete="off"></div>'
                '<p class="form-msg" role="status" aria-live="polite"></p>'
                f'<p class="fine">Your download starts right here, nothing to wait for. '
                f'<a href="{attr(self.site["studio"]["privacy_url"])}" rel="noopener">Privacy</a></p>'
                "</form>"
                f'<div class="gate-done" hidden><p class="gate-done-text">It’s yours.</p>'
                f'<div class="gate-links">{dl}</div></div>'
                "</dialog>")
        out = gate("playbook", "Free PDF", "The cold outreach playbook",
                   "All five pieces in one document: the audit, what failed, signal-based targeting, "
                   "the audit-first method and the Quest email.",
                   "The cold outreach playbook (PDF)",
                   [("Download the playbook (PDF)", d["playbook_pdf"], "cold-outreach-playbook.pdf")])
        if page.path == "tools/outreach-crm/index.html":
            out += gate("template", "Free download", "The CRM template and sequence structure",
                        "The two-touch CRM as a spreadsheet template (CSV, opens in Sheets, Excel or Numbers), "
                        "plus the outreach sequence structure as a two-page PDF.",
                        "Two-touch CRM template + outreach sequence structure",
                        [("CRM template (.csv)", d["crm_template_csv"], "two-touch-crm-template.csv"),
                         ("Sequence structure (.pdf)", d["sequence_pdf"], "outreach-sequence-structure.pdf")])
            out += gate("crm", "Save and export", "Keep your list",
                        "Saving to this browser and exporting your list are free. They need your email once.",
                        "Unlocked save/export in the two-touch CRM", [])
        return out

    def config_json(self, page, extra=None):
        c = page.ctx
        cfg = {
            "leads": {"endpoint": self.site["leads"]["endpoint"], "liveHosts": self.site["leads"]["live_hosts"]},
            "dryRun": self.preview,
            "downloads": {k: c.url(v) for k, v in self.site["downloads"].items()},
            "windowDays": self.stats["method"]["window_days"]["value"],
            "pageUrl": c.canonical(page.url),
        }
        if extra:
            cfg.update(extra)
        return ('<script type="application/json" id="ot-config">'
                + json.dumps(cfg, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/")
                + "</script>")

    def document(self, page, head, main, config_extra=None):
        return "\n".join([
            head,
            "<body>",
            GENERATED_NOTE.format(src=page.src),
            self.masthead(page),
            f'<main id="main" class="main main--{page.kind}">',
            main,
            "</main>",
            self.footer(page),
            self.gates(page),
            '<div class="toast" role="status" aria-live="polite" hidden></div>',
            self.config_json(page, config_extra),
            "</body>",
            "</html>",
            "",
        ])

    # json-ld ------------------------------------------------------------------
    def person(self):
        a = self.site["author"]
        return {"@type": "Person", "name": a["name"], "url": a["linkedin"],
                "sameAs": [a["linkedin"], a["medium"]], "jobTitle": "Founder",
                "worksFor": {"@type": "Organization", "name": self.site["studio"]["name"],
                             "url": "https://soniconsultancyservices.com/"}}

    def breadcrumbs(self, trail):
        return {"@type": "BreadcrumbList", "itemListElement": [
            {"@type": "ListItem", "position": i, "name": name, "item": self.site["base_url"] + url}
            for i, (name, url) in enumerate(trail, 1)]}

    # figures ------------------------------------------------------------------
    def render_count(self, ctx):
        a = self.stats["audit"]
        total = a["threads"]["value"]
        rows = []
        for key in ("positive", "engaged", "auto_replies", "rejections", "wrong_audience", "silence"):
            e = a[key]
            v = e["value"]
            floor = e["display"].endswith("+")
            pct = v / total * 100
            share = "0%" if v == 0 else ("under 1%" if pct < 1 else f"{pct:.0f}%")
            share = ("at least " if floor else "") + share
            rows.append(
                f'<li class="count-row{" is-zero" if v == 0 else ""}">'
                f'<span class="count-label">{esc(e["label"])}<span class="count-note">{esc(e["note"])}</span></span>'
                f'<span class="count-bar" aria-hidden="true"><span class="count-fill" style="--w:{pct:.2f}%"></span></span>'
                f'<span class="count-num"><span class="count-val">{esc(e["display"])}</span>'
                f'<span class="count-share">{esc(share)}</span></span></li>')
        return (
            '<figure class="count">'
            f'<figcaption class="count-cap"><span class="count-title">What happened in {total} starred threads</span>'
            f'<span class="count-key">Each bar is out of {total}. A + means at least that many.</span></figcaption>'
            f'<ol class="count-rows">{"".join(rows)}</ol></figure>')

    def render_timeline(self):
        window = self.stats["method"]["window_days"]["value"]
        early, late = 3, 120
        span = max(150, int(math.ceil((late + 30) / 30.0) * 30))

        def x(day):
            return f"{day / span * 100:.3f}%"
        ticks = "".join(f'<span class="tl-tick" style="--x:{x(d)}">{d}</span>' for d in range(0, span + 1, 30))
        return (
            '<figure class="timeline">'
            f'<figcaption class="tl-cap">The same email, sent on day {early} and on day {late} after a launch</figcaption>'
            f'<div class="tl" role="img" aria-label="Timeline from day 0 to day {span} after a launch. '
            f'The first {window} days are the window, when attention to the site starts high and fades. '
            f'Day {early} is at the start of the window. Day {late} is past it, in background noise.">'
            '<div class="tl-track">'
            f'<span class="tl-band tl-window" style="--x:0%;--w:{x(window)}"></span>'
            f'<span class="tl-band tl-noise" style="--x:{x(window)};--w:{x(span - window)}"></span>'
            f'<span class="tl-mark tl-mark--early" style="--x:{x(early)}"><span class="tl-mark-label">Day {early}</span></span>'
            f'<span class="tl-mark tl-mark--late" style="--x:{x(late)}"><span class="tl-mark-label">Day {late}</span></span>'
            "</div>"
            '<div class="tl-bands" aria-hidden="true">'
            f'<span class="tl-band-label" style="--x:0%;--w:{x(window)}">The window</span>'
            f'<span class="tl-band-label tl-band-label--noise" style="--x:{x(window)};--w:{x(span - window)}">Background noise</span>'
            "</div>"
            f'<div class="tl-axis" aria-hidden="true">{ticks}</div>'
            '<p class="tl-axis-title" aria-hidden="true">Days since launch</p>'
            "</div>"
            '<dl class="tl-legend">'
            f"<div><dt>Day {early}</dt><dd>A note about their load time lands in a conversation they’re already having.</dd></div>"
            f"<div><dt>Day {late}</dt><dd>The same note reads like a stranger pointing at something they’ve stopped thinking about.</dd></div>"
            "</dl>"
            '<p class="tl-foot">Illustrative: the fade is a judgement, not measured data.</p>'
            "</figure>")

    # tools --------------------------------------------------------------------
    def render_tool_cards(self, ctx):
        return (
            '<ul class="tool-cards">'
            f'<li class="tool-card"><a href="{ctx.url("/tools/outreach-crm/")}">'
            '<span class="tool-kicker">CRM</span>'
            '<span class="tool-name">The two-touch CRM</span>'
            '<span class="tool-desc">Log prospects, touches and outcomes. Every prospect gets two touches, '
            'then the thread closes. There’s no button for a third.</span>'
            '<span class="touches" aria-hidden="true"><span class="touch is-on"></span><span class="touch is-on"></span>'
            '<span class="touch-cap">cap</span></span>'
            f'<span class="tool-go">Open the CRM {ICON["arrow"]}</span></a></li>'
            f'<li class="tool-card"><a href="{ctx.url("/tools/prospect-scorer/")}">'
            '<span class="tool-kicker">Scorer</span>'
            '<span class="tool-name">Prospect scorer</span>'
            '<span class="tool-desc">Signal type, company size and days since the trigger. You get a score '
            'from 1 to 10 and the reason, before you spend time on an audit.</span>'
            '<span class="meter meter--mini" aria-hidden="true">'
            + "".join(f'<span class="meter-seg{" is-on" if i < 8 else ""}"></span>' for i in range(10))
            + f'</span><span class="tool-go">Score a prospect {ICON["arrow"]}</span></a></li>'
            "</ul>")

    def render_scorer_app(self, ctx):
        sc = self.stats["scorer"]
        sig = "".join(
            f'<label class="choice"><input type="radio" name="signal" value="{attr(s["id"])}"'
            f'{" checked" if s["id"] == "launch" else ""}><span class="choice-body">'
            f'<span class="choice-name">{esc(s["label"])}</span>'
            + (f'<span class="choice-eg">“{esc(s["example"])}”</span>' if s["example"] else
               '<span class="choice-eg">No trigger event</span>')
            + "</span></label>" for s in sc["signals"])
        size = "".join(
            f'<label class="seg"><input type="radio" name="size" value="{attr(z["id"])}"'
            f'{" checked" if z["id"] == "11-50" else ""}><span>{esc(z["label"].replace(" people", ""))}</span></label>'
            for z in sc["sizes"])
        return (
            '<div class="scorer" data-scorer>'
            '<form class="scorer-form" data-scorer-form novalidate>'
            '<fieldset class="scorer-field"><legend>What did they say?</legend>'
            f'<div class="choices">{sig}</div></fieldset>'
            '<fieldset class="scorer-field"><legend>Company size <span class="legend-note">people</span></legend>'
            f'<div class="segs">{size}</div></fieldset>'
            '<div class="scorer-field scorer-days"><label class="legend" for="sc-days">Days since the trigger</label>'
            '<div class="days-row"><input id="sc-days" name="days" type="number" inputmode="numeric" min="0" max="999" value="3">'
            '<input id="sc-days-range" type="range" min="0" max="365" value="3" aria-label="Days since the trigger, slider">'
            '</div><p class="days-presets" aria-label="Examples">'
            '<button type="button" class="chip" data-days="3">Day 3</button>'
            '<button type="button" class="chip" data-days="30">Day 30</button>'
            '<button type="button" class="chip" data-days="120">Day 120</button></p>'
            '<p class="days-note" data-days-note hidden>A job title alone has no trigger date, so timing doesn’t count.</p>'
            "</div></form>"
            '<section class="scorer-out" aria-live="polite" aria-label="Score">'
            '<p class="scorer-example" data-example>Example inputs. Change anything to score your own prospect.</p>'
            '<div class="score-row"><p class="score"><span class="score-num" data-score>10</span><span class="score-of">/10</span></p>'
            '<p class="score-verdict" data-verdict>Audit it today</p></div>'
            '<div class="meter" data-meter aria-hidden="true">'
            + "".join('<span class="meter-seg"></span>' for _ in range(10))
            + "</div>"
            '<p class="score-reason" data-reason></p>'
            '<table class="score-parts"><caption class="sr-only">How the score adds up</caption><tbody>'
            '<tr><th scope="row">Signal</th><td data-part="signal"></td><td class="pts" data-pts="signal"></td></tr>'
            '<tr><th scope="row">Company size</th><td data-part="size"></td><td class="pts" data-pts="size"></td></tr>'
            '<tr><th scope="row">Timing</th><td data-part="timing"></td><td class="pts" data-pts="timing"></td></tr>'
            '<tr class="total"><th scope="row">Score</th><td>clamped to 1–10</td><td class="pts" data-pts="total"></td></tr>'
            "</tbody></table>"
            '<div class="mini-tl" aria-hidden="true"><span class="mini-tl-window"></span>'
            '<span class="mini-tl-mark" data-mini-mark></span></div>'
            '<p class="mini-tl-cap" data-mini-cap></p>'
            '<p class="scorer-share"><button type="button" class="btn btn--quiet" data-copy-link>'
            f'{ICON["link"]}<span>Copy link to this score</span></button></p>'
            "</section>"
            '<noscript><p class="noscript">The scorer needs JavaScript. The weights are listed below if you’d rather add it up by hand.</p></noscript>'
            "</div>")

    def render_scorer_weights(self):
        sc = self.stats["scorer"]
        window = self.stats["method"]["window_days"]["value"]

        def pts(p):
            return f"+{p}" if p > 0 else ("0" if p == 0 else f"−{abs(p)}")
        sig = "".join(f'<tr><th scope="row">{esc(s["label"])}</th><td class="pts">{pts(s["points"])}</td></tr>'
                      for s in sc["signals"])
        size = "".join(f'<tr><th scope="row">{esc(z["label"])}</th><td class="pts">{pts(z["points"])}</td></tr>'
                       for z in sc["sizes"])
        rows, lo = [], 0
        for b in sc["timing"]:
            hi = b["max_days"]
            label = f"Day {lo}–{hi}" if hi is not None else f"Day {lo}+"
            note = " (end of the window)" if hi == window else ""
            rows.append(f'<tr><th scope="row">{label}{note}</th><td class="pts">{pts(b["points"])}</td></tr>')
            lo = (hi or 0) + 1
        return (
            '<div class="weights">'
            f'<table><caption>Signal</caption><tbody>{sig}</tbody></table>'
            f'<table><caption>Company size</caption><tbody>{size}</tbody></table>'
            f'<table><caption>Days since the trigger</caption><tbody>{"".join(rows)}</tbody></table>'
            "</div>")

    def render_crm_app(self, ctx):
        sc = self.stats["scorer"]
        sig_opts = "".join(f'<option value="{attr(s["id"])}">{esc(s["label"])}</option>' for s in sc["signals"])
        size_opts = "".join(f'<option value="{attr(z["id"])}"{" selected" if z["id"] == "11-50" else ""}>'
                            f'{esc(z["label"])}</option>' for z in sc["sizes"])
        return (
            '<div class="crm" data-crm>'
            '<div class="crm-banner" data-crm-banner></div>'
            '<section class="crm-count" aria-label="Your honest count">'
            '<p class="crm-count-title">Your honest count</p>'
            '<dl class="crm-count-grid" data-crm-count></dl></section>'
            '<div class="crm-toolbar">'
            '<div class="crm-filters" role="group" aria-label="Show">'
            '<button type="button" class="chip is-on" data-filter="all" aria-pressed="true">All</button>'
            '<button type="button" class="chip" data-filter="todo" aria-pressed="false">To contact</button>'
            '<button type="button" class="chip" data-filter="waiting" aria-pressed="false">Waiting</button>'
            '<button type="button" class="chip" data-filter="replied" aria-pressed="false">Replied</button>'
            '<button type="button" class="chip" data-filter="closed" aria-pressed="false">Closed</button></div>'
            '<div class="crm-actions">'
            '<button type="button" class="btn" data-crm-add-toggle aria-expanded="false" aria-controls="crm-add">Add prospect</button>'
            '<button type="button" class="btn btn--quiet" data-crm-save>Save to this browser</button>'
            '<button type="button" class="btn btn--quiet" data-crm-export="csv">Export CSV</button>'
            '<button type="button" class="btn btn--quiet" data-crm-export="json">Export JSON</button>'
            '<label class="btn btn--quiet file-btn">Import<input type="file" accept=".csv,.json,text/csv,application/json" data-crm-import></label>'
            "</div></div>"
            '<form class="crm-add" id="crm-add" data-crm-add hidden novalidate>'
            '<p class="crm-add-title">New prospect</p>'
            '<div class="crm-grid">'
            '<label>Name<input name="name" autocomplete="off" required placeholder="Who you’d write to"></label>'
            '<label>Company<input name="company" autocomplete="off" required placeholder="Company"></label>'
            '<label>Role<input name="role" autocomplete="off" placeholder="Founder, CTO…" data-role-input></label>'
            '<label>Email or LinkedIn URL<input name="contact" autocomplete="off" placeholder="How you reach them"></label>'
            f'<label>Signal type<select name="signal_type">{sig_opts}</select></label>'
            f'<label>Company size<select name="size">{size_opts}</select></label>'
            '<label class="span-2">What did they say?<input name="signal_quote" autocomplete="off" placeholder="e.g. our site is so slow"></label>'
            '<label>Signal date<input name="trigger_date" type="date"></label>'
            "</div>"
            '<p class="crm-warn" data-role-warn hidden>Recruiters fill seats. They rarely buy from a studio, '
            'so check who’s actually behind the post before you write.</p>'
            '<p class="form-msg" role="status" aria-live="polite"></p>'
            '<div class="crm-add-actions"><button class="btn" type="submit">Add to list</button>'
            '<button class="btn btn--quiet" type="button" data-crm-add-cancel>Cancel</button></div>'
            "</form>"
            '<ol class="crm-list" data-crm-list aria-live="polite"></ol>'
            '<p class="crm-empty" data-crm-empty hidden></p>'
            '<noscript><p class="noscript">The CRM runs in your browser and needs JavaScript.</p></noscript>'
            "</div>")

    def render_template_download(self, ctx):
        return (
            '<section class="capture capture--asset" aria-labelledby="tpl-h">'
            '<div class="asset-art" aria-hidden="true"><span class="asset-sheet"></span><span class="asset-sheet"></span></div>'
            '<div class="asset-body">'
            '<h2 class="capture-title" id="tpl-h">Take the CRM with you</h2>'
            '<p class="capture-text">The same columns and rules as a spreadsheet template, plus the outreach '
            'sequence structure: what goes in touch one, what touch two has to add, and when a thread closes.</p>'
            f'<button type="button" class="btn" data-gate="template">{ICON["download"]}'
            "<span>Get the template and sequence</span></button></div></section>")

    def render_studio_cta(self, ctx):
        return (
            '<aside class="studio-cta" aria-label="Work with me">'
            '<p>Want a tool like this built for your own workflow? '
            f'<a href="{attr(self.site["studio"]["cta_url"])}" rel="noopener">I build these for a living'
            f'{ICON["arrow"]}</a></p></aside>')

    # page renderers -------------------------------------------------------------
    def article_page(self, page, articles):
        m = page.meta
        md = Markdown(page, self)
        body = md.render(page.body_md)
        idx = articles.index(page)
        flagship = articles[0]
        is_flag = page is flagship
        lo, hi = WORD_TARGETS.get(m["slug"], (None, None))
        if lo and m["words"] < lo or hi and m["words"] > hi:
            self.warnings.append(f"{page.path}: {m['words']} words, brief target {lo}–{hi or '∞'}")
        c = page.ctx
        # "Deep dive" pieces expand a numbered section of the flagship.
        kicker = esc(m.get("kicker", ""))
        if not is_flag:
            sec_no = m["order"]
            flag_sections = self.flag_sections
            if sec_no - 1 < len(flag_sections):
                _, sec_title, sec_id = flag_sections[sec_no - 1]
                kicker = (f'{esc(m.get("kicker", ""))} <span class="kicker-sep">/</span> '
                          f'<a href="{c.url(flagship.url + "#" + sec_id)}">expands §{sec_no} of the audit</a>')
        toc = ""
        if m.get("toc") == "true":
            items = "".join(f'<li><a href="#{hid}">{esc(text)}</a></li>'
                            for level, text, hid in md.headings if level == 2)
            toc = (f'<nav class="toc" aria-labelledby="toc-h"><p class="toc-title" id="toc-h">In this piece</p>'
                   f"<ol>{items}</ol></nav>")
        prev_p = articles[idx - 1] if idx > 0 else None
        next_p = articles[idx + 1] if idx + 1 < len(articles) else None

        def nav_card(p, label):
            if not p:
                return "<span></span>"
            return (f'<a class="next-card" href="{c.url(p.url)}"><span class="next-label">{label}</span>'
                    f'<span class="next-title">{esc(p.meta["title"])}</span>'
                    f'<span class="next-meta">{p.meta["minutes"]} min read</span></a>')
        share_url = c.canonical(page.url)
        share = (
            '<div class="share"><p class="share-label">Share this piece</p>'
            '<a class="btn btn--quiet" rel="noopener" href="https://www.linkedin.com/sharing/share-offsite/?url='
            f'{attr(share_url)}">{ICON["share"]}<span>Share on LinkedIn</span></a>'
            f'<button class="btn btn--quiet" type="button" data-copy="{attr(share_url)}">{ICON["link"]}'
            "<span>Copy link</span></button></div>")
        main = (
            '<article class="post">'
            '<header class="post-head">'
            f'<p class="kicker">{kicker}</p>'
            f'<h1 class="post-title">{esc(m["title"])}</h1>'
            f'<p class="dek">{esc(m["dek"])}</p>'
            '<dl class="post-meta">'
            f'<div><dt>From</dt><dd><a href="{attr(self.site["author"]["linkedin"])}" rel="noopener">'
            f'{esc(self.site["author"]["name"])}</a></dd></div>'
            f'<div><dt>Date</dt><dd><time datetime="{m["date"]}">{fmt_date(m["date"])}</time></dd></div>'
            f'<div><dt>Read</dt><dd>{m["minutes"]} min</dd></div>'
            "</dl></header>"
            f"{toc}"
            f'<div class="prose">{body}</div>'
            '<footer class="post-foot">'
            f"{share}"
            f'<section class="capture capture--article">{self.newsletter_form("end", "article")}'
            '<p class="capture-alt">Rather have all five pieces in one file? '
            '<button class="linkish" type="button" data-gate="playbook">Get the playbook as a PDF</button></p>'
            "</section>"
            f'<nav class="next-read" aria-label="More pieces">{nav_card(prev_p, "Previous")}{nav_card(next_p, "Next")}</nav>'
            "</footer></article>")
        jsonld = {"@context": "https://schema.org", "@graph": [
            {"@type": "BlogPosting", "headline": m["title"], "description": m["description"],
             "datePublished": m["date"], "dateModified": m["date"], "inLanguage": "en",
             "wordCount": m["words"], "author": self.person(),
             "mainEntityOfPage": c.canonical(page.url),
             "image": self.site["base_url"] + f"/assets/og/{m['slug']}.png",
             "isPartOf": {"@type": "WebSite", "name": self.site["name"], "url": self.site["base_url"] + "/"}},
            self.breadcrumbs([("Home", "/"), ("Articles", "/articles/"), (m["title"], page.url)]),
        ]}
        head = self.head(page, m["seo_title"], m["description"], "article", f"/assets/og/{m['slug']}.png", jsonld)
        self.write(page.path, self.document(page, head, main))
        page.html_body = body

    def home_page(self, page, articles):
        m = page.meta
        c = page.ctx
        md = Markdown(page, self)
        thesis = md.render(page.body_md)
        flag = articles[0]
        a = self.stats["audit"]
        tally_keys = ("threads", "positive", "engaged", "auto_replies", "rejections", "wrong_audience", "silence")
        tally_names = {"threads": "threads read", "positive": "positive replies", "engaged": "real conversation",
                       "auto_replies": "auto-replies", "rejections": "said no", "wrong_audience": "wrong audience",
                       "silence": "silence"}
        tally = "".join(f'<li><span class="tally-n">{esc(a[k]["display"])}</span>'
                        f'<span class="tally-l">{tally_names[k]}</span></li>' for k in tally_keys)
        dives = "".join(
            f'<li><a class="dive" href="{c.url(p.url)}">'
            f'<span class="dive-sec">§{p.meta["order"]}</span>'
            f'<span class="dive-title">{esc(p.meta["title"])}</span>'
            f'<span class="dive-sum">{esc(p.meta["summary"])}</span>'
            f'<span class="dive-meta">{p.meta["minutes"]} min read</span></a></li>'
            for p in articles[1:])
        main = (
            '<section class="hero" aria-labelledby="hero-h">'
            f'<p class="kicker">{esc(m["kicker"])}</p>'
            f'<h1 class="hero-title" id="hero-h">{esc(m["title"])}</h1>'
            f'<div class="hero-body">{thesis}</div>'
            f'<p class="hero-cta"><a class="btn btn--lg" href="{c.url(flag.url)}">Read the audit{ICON["arrow"]}</a>'
            f'<span class="hero-meta">{flag.meta["minutes"]} min read</span></p>'
            f'<ul class="tally" aria-label="The count">{tally}</ul>'
            "</section>"
            '<section class="dives" aria-labelledby="dives-h">'
            '<div class="section-head"><h2 id="dives-h">The deep dives</h2>'
            '<p>Sections two to five of the audit, each expanded into a piece you can act on today.</p></div>'
            f'<ol class="dive-list">{dives}</ol></section>'
            '<section class="home-tools" aria-labelledby="tools-h">'
            '<div class="section-head"><h2 id="tools-h">The tools</h2>'
            '<p>Two pieces of the system you can use right now. Both run in your browser, no login.</p></div>'
            f"{self.render_tool_cards(c)}</section>"
            '<section class="playbook-card" aria-labelledby="pb-h">'
            '<div class="pb-art" aria-hidden="true"><span class="pb-page"></span><span class="pb-page"></span><span class="pb-page"></span></div>'
            '<div class="pb-body"><h2 id="pb-h">The whole playbook, one PDF</h2>'
            '<p>All five pieces in one document you can keep, print or forward to the person who does your outbound.</p>'
            f'<button type="button" class="btn" data-gate="playbook">{ICON["download"]}<span>Get the playbook</span></button></div>'
            "</section>")
        jsonld = {"@context": "https://schema.org", "@graph": [
            {"@type": "WebSite", "name": self.site["name"], "url": self.site["base_url"] + "/",
             "description": m["description"], "inLanguage": "en", "author": self.person()},
            self.person(),
        ]}
        head = self.head(page, m["seo_title"], m["description"], "website", "/assets/og/home.png", jsonld)
        self.write(page.path, self.document(page, head, main))

    def articles_index(self, articles):
        path = "articles/index.html"
        page = Page(path, "build.py (article list)", "index", {"title": "Articles"}, "", self.ctx(path))
        c = page.ctx
        def sec(p):
            return f"§{p.meta['order']}" if p.meta["order"] > 1 else "Start"
        items = "".join(
            f'<li><a class="dive" href="{c.url(p.url)}">'
            f'<span class="dive-sec">{sec(p)}</span>'
            f'<span class="dive-title">{esc(p.meta["title"])}</span>'
            f'<span class="dive-sum">{esc(p.meta["summary"])}</span>'
            f'<span class="dive-meta">{p.meta["minutes"]} min read</span></a></li>'
            for p in articles)
        desc = self.t("Five pieces on cold outreach from an audit of {{threads}} of my own threads: what failed, "
                      "signal-based targeting, the audit-first method and the one email that worked.")
        main = (
            '<header class="page-head"><p class="kicker">Articles</p>'
            '<h1 class="page-title">The audit, and four deep dives</h1>'
            '<p class="dek">Start with the audit. Each deep dive expands one of its sections into something you can act on today.</p></header>'
            f'<ol class="dive-list dive-list--all">{items}</ol>'
            '<p class="capture-alt capture-alt--index">Rather read them offline? '
            '<button class="linkish" type="button" data-gate="playbook">Get all five as one PDF</button></p>')
        jsonld = {"@context": "https://schema.org", "@graph": [
            {"@type": "CollectionPage", "name": "Articles", "url": c.canonical(page.url), "description": desc},
            self.breadcrumbs([("Home", "/"), ("Articles", "/articles/")])]}
        head = self.head(page, "Articles on cold outreach", desc, "website", "/assets/og/home.png", jsonld)
        self.write(path, self.document(page, head, main))

    def tool_page(self, page, crumbs, og_slug, app_schema=None, scripts=()):
        m = page.meta
        md = Markdown(page, self)
        body = md.render(page.body_md)
        c = page.ctx
        main = (
            f'<header class="page-head"><p class="kicker">{esc(m["kicker"])}</p>'
            f'<h1 class="page-title">{esc(m["title"])}</h1>'
            f'<p class="dek">{esc(m["dek"])}</p></header>'
            f'<div class="prose prose--tool">{body}</div>')
        graph = [self.breadcrumbs(crumbs)]
        if app_schema:
            graph.insert(0, {"@type": "WebApplication", "name": m["title"], "url": c.canonical(page.url),
                             "description": m["description"], "applicationCategory": "BusinessApplication",
                             "operatingSystem": "Any (runs in the browser)", "isAccessibleForFree": True,
                             "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
                             "author": self.person()})
        else:
            graph.insert(0, {"@type": "CollectionPage", "name": m["title"], "url": c.canonical(page.url),
                             "description": m["description"]})
        jsonld = {"@context": "https://schema.org", "@graph": graph}
        head = self.head(page, m["seo_title"], m["description"], "website", f"/assets/og/{og_slug}.png",
                         jsonld, scripts)
        extra = None
        if app_schema:
            extra = {"scorer": self.stats["scorer"]}
            if page.path == "tools/outreach-crm/index.html":
                extra["crmColumns"] = self.site["crm_columns"]
        self.write(page.path, self.document(page, head, main, extra))

    def not_found(self):
        path = "404.html"
        page = Page(path, "build.py (404)", "404", {"title": "Not found"}, "", self.ctx(path))
        c = page.ctx
        main = (
            '<header class="page-head page-head--404"><p class="kicker">404</p>'
            '<h1 class="page-title">No thread here.</h1>'
            '<p class="dek">This page doesn’t exist, or it moved. Everything that does exist is one click away.</p></header>'
            f'<ul class="lost-links"><li><a href="{c.url("/articles/the-audit/")}">Read the audit</a></li>'
            f'<li><a href="{c.url("/articles/")}">All articles</a></li>'
            f'<li><a href="{c.url("/tools/")}">The tools</a></li>'
            f'<li><a href="{c.url("/")}">Home</a></li></ul>')
        jsonld = {"@context": "https://schema.org", "@type": "WebPage", "name": "Not found"}
        head = self.head(page, "Page not found", "This page doesn\u2019t exist, or it moved. The audit, the deep dives and the tools are one click away.", "website", "/assets/og/home.png", jsonld)
        self.write(path, self.document(page, head, main))

    # site files -----------------------------------------------------------------
    def sitemap(self, pages):
        base = self.site["base_url"]
        rows = "".join(f"<url><loc>{esc(base + p.url)}</loc><lastmod>{p.meta.get('date', self.site['published'])}</lastmod></url>\n"
                       for p in pages)
        self.write("sitemap.xml", '<?xml version="1.0" encoding="UTF-8"?>\n'
                   '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + rows + "</urlset>\n")
        self.write("robots.txt",
                   "# generated by build.py\nUser-agent: *\nAllow: /\n"
                   "# Gated downloads are revealed after an email; keep them out of search results.\n"
                   f"Disallow: /downloads/\n\nSitemap: {base}/sitemap.xml\n")

    def llms_txt(self, articles, tools):
        base = self.site["base_url"]
        lines = [f"# {self.site['name']}", "",
                 self.t("> A teardown of Het Soni's own cold outreach: an audit of {{threads}} threads, the five "
                        "causes of failure in order of damage, and the system rebuilt from it."), "",
                 "## Articles", ""]
        for p in articles:
            lines.append(f"- [{p.meta['title']}]({base}{p.url}): {p.meta['summary']}")
        lines += ["", "## Tools", ""]
        for p in tools:
            lines.append(f"- [{p.meta['title']}]({base}{p.url}): {p.meta['description']}")
        lines += ["", "## Author", "",
                  f"- {self.site['author']['name']}, founder of {self.site['studio']['name']} "
                  f"(https://soniconsultancyservices.com/). LinkedIn: {self.site['author']['linkedin']}", ""]
        self.write("llms.txt", "\n".join(lines))

    # checks -----------------------------------------------------------------------
    def check_links(self):
        """Every internal href/src must point at a file this build produced or one in public/,
        and every #fragment must exist on its target page."""
        ids, problems = {}, []
        for rel in self.written:
            if rel.endswith(".html"):
                ids[rel] = set(re.findall(r'\sid="([^"]+)"', (self.out / rel).read_text("utf-8")))
        for rel in self.written:
            if not rel.endswith(".html"):
                continue
            text = (self.out / rel).read_text("utf-8")
            for ref in re.findall(r'\s(?:href|src)="([^"]+)"', text):
                if ref.startswith(("http:", "https:", "mailto:", "data:", "tel:")):
                    continue
                path, _, frag = ref.partition("#")
                path = path.split("?")[0]
                if self.preview:
                    target = os.path.normpath(os.path.join(os.path.dirname(rel), path)) if path else rel
                else:
                    target = (path.lstrip("/") + ("index.html" if path.endswith("/") else "")) if path else rel
                exists = target in ids or (self.out / target).exists() or (PUBLIC / target).exists()
                if not exists and target.startswith("downloads/"):
                    self.warnings.append(f"{rel}: {ref} does not exist yet (run `python3 build.py --assets`)")
                elif not exists:
                    problems.append(f"{rel}: broken link {ref}")
                elif frag and target in ids and frag not in ids[target]:
                    problems.append(f"{rel}: #{frag} not found on {target}")
        if problems:
            raise BuildError("link check failed:\n  " + "\n  ".join(sorted(set(problems))))

    def check_directives(self):
        uses = self.directive_use.get("studio-cta", [])
        if uses != ["tools/outreach-crm/index.html"]:
            raise BuildError("the studio CTA must appear exactly once, on /tools/outreach-crm/ "
                             f"(found on: {uses or 'no page'})")

    # orchestration ----------------------------------------------------------------
    def run(self):
        articles = self.load_articles()
        # Render the flagship first so the deep dives can link to its section anchors.
        flag = articles[0]
        probe = Markdown(flag, self)
        probe.render(flag.body_md)
        self.flag_sections = [h for h in probe.headings if h[0] == 2]
        self.directive_use = {}

        home = self.load_page("home.md", "index.html", "home")
        tools_index = self.load_page("tools/index.md", "tools/index.html", "tools")
        crm = self.load_page("tools/outreach-crm.md", "tools/outreach-crm/index.html", "tool")
        scorer = self.load_page("tools/prospect-scorer.md", "tools/prospect-scorer/index.html", "tool")

        for p in articles:
            self.article_page(p, articles)
        self.home_page(home, articles)
        self.articles_index(articles)
        self.tool_page(tools_index, [("Home", "/"), ("Tools", "/tools/")], "tools")
        self.tool_page(crm, [("Home", "/"), ("Tools", "/tools/"), (crm.meta["title"], crm.url)], "outreach-crm",
                       app_schema=True, scripts=("/assets/js/score.js", "/assets/js/crm.js"))
        self.tool_page(scorer, [("Home", "/"), ("Tools", "/tools/"), (scorer.meta["title"], scorer.url)],
                       "prospect-scorer", app_schema=True, scripts=("/assets/js/score.js", "/assets/js/scorer.js"))
        self.not_found()
        listed = [home] + articles + [tools_index, crm, scorer]
        index_page = Page("articles/index.html", "", "index", {}, "", self.ctx("articles/index.html"))
        self.sitemap(listed[:1] + [index_page] + listed[1:])
        self.llms_txt(articles, [crm, scorer])
        if self.out != PUBLIC:
            self.copy_static()
        self.check_directives()
        self.check_links()
        self.articles, self.home = articles, home
        return self

    def copy_static(self):
        for rel in ("assets", "downloads", "favicon.svg"):
            src = PUBLIC / rel
            dest = self.out / rel
            if not src.exists():
                continue
            if src.is_dir():
                shutil.copytree(src, dest, dirs_exist_ok=True)
            else:
                shutil.copy2(src, dest)
        if self.preview and self.inline_fonts:
            css = self.out / "assets/css/site.css"
            text = css.read_text("utf-8")

            def embed(m):
                font = PUBLIC / "assets/fonts" / m.group(1)
                return "url(data:font/woff2;base64," + base64.b64encode(font.read_bytes()).decode() + ")"
            css.write_text(re.sub(r"url\(/assets/fonts/([\w.-]+\.woff2)\)", embed, text), "utf-8")
        elif self.preview:
            css = self.out / "assets/css/site.css"
            css.write_text(css.read_text("utf-8").replace("url(/assets/fonts/", "url(../fonts/"), "utf-8")


THEME_BOOT = ("(function(){try{var t=localStorage.getItem('ot-theme');"
              "if(t==='dark'||t==='light')document.documentElement.setAttribute('data-theme',t)}catch(e){}})();")


# ------------------------------------------------------------------ chrome assets
def find_chrome():
    env = os.environ.get("CHROME_PATH")
    candidates = [env] if env else []
    candidates += [
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "/Applications/Chromium.app/Contents/MacOS/Chromium",
        shutil.which("google-chrome") or "", shutil.which("chromium") or "",
        shutil.which("chromium-browser") or "", "/opt/pw-browsers/chromium",
    ]
    pw = Path("/opt/pw-browsers")
    if pw.exists():
        candidates += [str(p) for p in sorted(pw.glob("chromium-*/chrome-linux/chrome"))]
    for c in candidates:
        if c and Path(c).is_file() and os.access(c, os.X_OK):
            return c
    return None


def chrome_run(chrome, args):
    base = [chrome, "--headless=new", "--disable-gpu", "--hide-scrollbars", "--no-first-run",
            "--no-default-browser-check", "--virtual-time-budget=8000", "--run-all-compositor-stages-before-draw"]
    if hasattr(os, "geteuid") and os.geteuid() == 0:
        base.append("--no-sandbox")
    res = subprocess.run(base + args, capture_output=True, text=True, timeout=180)
    if res.returncode != 0:
        raise BuildError("Chrome failed: " + (res.stderr or res.stdout)[-800:])


def crop_png(path, height):
    """Keep the top `height` rows of a PNG (stdlib only). Chrome's new headless mode
    reserves ~87px of phantom browser UI, so share images are rendered in a taller
    window and cropped back to 630px here."""
    import struct
    import zlib
    data = Path(path).read_bytes()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise BuildError(f"{path} is not a PNG")
    pos, chunks = 8, []
    while pos < len(data):
        length = struct.unpack(">I", data[pos:pos + 4])[0]
        ctype = data[pos + 4:pos + 8]
        chunks.append((ctype, data[pos + 8:pos + 8 + length]))
        pos += 12 + length
    ihdr = chunks[0][1]
    width, old_h, depth, color, _, _, interlace = struct.unpack(">IIBBBBB", ihdr)
    if interlace or depth != 8 or color not in (2, 6) or height > old_h:
        raise BuildError(f"{path}: unexpected PNG format for cropping")
    stride = 1 + width * (4 if color == 6 else 3)
    raw = zlib.decompress(b"".join(c for t, c in chunks if t == b"IDAT"))
    body = zlib.compress(raw[:stride * height], 9)

    def chunk(ctype, payload):
        return (struct.pack(">I", len(payload)) + ctype + payload
                + struct.pack(">I", zlib.crc32(ctype + payload) & 0xFFFFFFFF))
    out = data[:8] + chunk(b"IHDR", struct.pack(">II", width, height) + ihdr[8:])
    for ctype, payload in chunks[1:]:
        if ctype not in (b"IDAT", b"IEND"):
            out += chunk(ctype, payload)
    out += chunk(b"IDAT", body) + chunk(b"IEND", b"")
    Path(path).write_bytes(out)


def render_assets(build):
    """PDFs and share images, rendered by headless Chrome from generated print/OG pages."""
    chrome = find_chrome()
    if not chrome:
        raise BuildError("--assets needs Chrome or Chromium. Set CHROME_PATH=/path/to/chrome.")
    import assets as asset_templates  # templates/assets.py, kept separate to keep this file readable
    work = Path(tempfile.mkdtemp(prefix="outreach-assets-"))
    try:
        jobs = asset_templates.jobs(build, work)
        for job in jobs:
            out = PUBLIC / job["out"]
            out.parent.mkdir(parents=True, exist_ok=True)
            if job["kind"] == "pdf":
                chrome_run(chrome, ["--no-pdf-header-footer", f"--print-to-pdf={out}", job["url"]])
            elif job["kind"] == "png":
                chrome_run(chrome, ["--window-size=1200,900", "--force-device-scale-factor=1",
                                    f"--screenshot={out}", job["url"]])
                crop_png(out, 630)
            elif job["kind"] == "text":
                out.write_text(job["text"], "utf-8")
            print(f"  asset  {job['out']}")
    finally:
        shutil.rmtree(work, ignore_errors=True)


# ------------------------------------------------------------------------ main
def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if public/ is out of date")
    ap.add_argument("--assets", action="store_true", help="also render PDFs, CSV and share images (needs Chrome)")
    ap.add_argument("--preview", metavar="DIR", help="build a self-contained preview copy into DIR")
    ap.add_argument("--inline-fonts", action="store_true", help="with --preview: embed fonts in the CSS")
    args = ap.parse_args(argv)
    sys.path.insert(0, str(TEMPLATES))
    try:
        if args.check:
            tmp = Path(tempfile.mkdtemp(prefix="outreach-check-"))
            try:
                b = Build(tmp).run()
                stale = [rel for rel in b.written
                         if not (PUBLIC / rel).exists() or (PUBLIC / rel).read_bytes() != (tmp / rel).read_bytes()]
            finally:
                shutil.rmtree(tmp, ignore_errors=True)
            if stale:
                print("public/ is out of date. Run `python3 build.py`. Stale files:\n  " + "\n  ".join(stale))
                return 1
            print(f"public/ is up to date ({len(b.written)} generated files).")
            return 0
        if args.preview:
            out = Path(args.preview).resolve()
            if out == PUBLIC.resolve():
                raise BuildError("--preview must not point at public/")
            if out.exists():
                shutil.rmtree(out)
            b = Build(out, preview=True, inline_fonts=args.inline_fonts).run()
            print(f"preview built into {out} ({len(b.written)} pages and files, links relative, forms in dry run)")
        else:
            b = Build(PUBLIC).run()
            print(f"built {len(b.written)} files into public/")
            if args.assets:
                render_assets(b)
        for p in b.articles:
            print(f"  {p.meta['slug']:<24} {p.meta['words']:>5} words  {p.meta['minutes']:>2} min")
        for w in b.warnings:
            print("  warning:", w)
        return 0
    except BuildError as e:
        print("build failed:", e, file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
